// Verify the JS SDK reproduces the shared golden fixture exactly.
//
// Reads tests/fixtures/assignment_golden.json (generated by Python) and
// checks that the JS `assign` returns the same variant for every case.
// Exits 0 on full parity, 1 on any mismatch. Used by the parity test and CI.
//
// Run:  node sdk/verify_parity.mjs

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { assign, fnv1a32 } from "./assign.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const golden = join(here, "..", "tests", "fixtures", "assignment_golden.json");

// Sanity: the FNV-1a known vectors must match before we trust anything.
const vectors = [
  ["", 0x811c9dc5],
  ["a", 0xe40c292c],
  ["foobar", 0xbf9cf968],
];
for (const [text, expected] of vectors) {
  if (fnv1a32(text) !== expected >>> 0) {
    console.error(`FNV vector mismatch for ${JSON.stringify(text)}`);
    process.exit(1);
  }
}

const cases = JSON.parse(readFileSync(golden, "utf-8"));
let mismatches = 0;
for (const c of cases) {
  const got = assign(c.experiment_id, c.user_id, c.variants);
  if (got !== c.expected) {
    mismatches++;
    if (mismatches <= 5) {
      console.error(
        `mismatch: ${c.experiment_id}/${c.user_id} ` +
          `expected=${c.expected} got=${got}`
      );
    }
  }
}

if (mismatches === 0) {
  console.log(`PARITY OK: JS matches all ${cases.length} Python cases`);
  process.exit(0);
} else {
  console.error(`PARITY FAILED: ${mismatches}/${cases.length} mismatches`);
  process.exit(1);
}
